### ISSUE TITLE
Incompatible with arm64 machines

### ISSUE THREAD

**Issue by OrigamingWasTaken** [kel-cu/SimplyStatus#11]
Hello, I'm using a Macbook Air M1 (arm64) and the game instantly crashes when launching.
Here are my logs:
https://mclo.gs/eAAeetL

**Comment by simply-kel** [comment]
The problem is in the library I use for Discord integration, maybe I'll look at forks and try to work on ARM architecture support (although I don't have an adequate ARM device except Raspberry Pi 4).

**Comment by OrigamingWasTaken** [comment]
If you need a device to test, I'll be happy to help you.

**Comment by OrigamingWasTaken** [comment]
Has this been fixed? Haven't tried the mod in a while

**Comment by kel-cu** [comment]
For now, the 2.1.x changes have been canceled due to poor code and optimization.
For now, the update has been postponed until another project is finalized, i.e. AlinLib 1.1.x for future conversion from YACL to AlinLib

**Comment by kel-cu** [comment]
Can I ask you to try [2.1.0-beta.1](https://modrinth.com/mod/simplystatus/version/2.1.0-beta.1), maybe the new library supports ARM, especially MacOS.

**Comment by OrigamingWasTaken** [comment]
I will try it right away when I can!

**Comment by kel-cu** [comment]
![image](https://github.com/simply-kel/SimplyStatus/assets/86980879/47e383d4-0e4c-4105-992e-ec05ef2f7685)

**Comment by kel-cu** [comment]
Issue closed due to inactivity

**Comment by OrigamingWasTaken** [comment]
Hey, sorry for the inactivity. I stopped playing minecraft and completely forgot about this issue. After testing the latest version of the mod, the crashes seem to be fixed. Thanks for you work 👍
