### ISSUE TITLE
Добавить возможность создания кнопок

### ISSUE THREAD

**Issue by DonorKrovi** [kel-cu/SimplyStatus#12]
Подобное есть в Simple Discord RPC в котором можно создать интерактивные кнопки которые используютсься как ссылки

**Comment by simply-kel** [comment]
Посмотрю такой вариант при изучении новой библиотеке, пока-что с текущей библиотекой для RPC такое нельзя сделать

**Comment by kel-cu** [comment]
Сделано в [коммите](https://github.com/kel-cu/SimplyStatus/commit/24a17e9bb0104410cebd84db8187f86a59f9428c)
